In [19]:
import numpy as np # type: ignore

In [20]:
# Sorting

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.sort(a) # sort in ascending
np.sort(a)[::-1] # sort in descending

np.sort(b) # row wise sorting
print(b)
np.sort(b, axis = 0) # row wise sorting 
np.sort(b, axis = 1) # col wise sorting 

[[46 18 47 14]
 [27 89 34 25]
 [29 93 82 48]
 [12 44 12 12]
 [33 54 82 60]
 [81 77 77 17]]


array([[14, 18, 46, 47],
       [25, 27, 34, 89],
       [29, 48, 82, 93],
       [12, 12, 12, 44],
       [33, 54, 60, 82],
       [17, 77, 77, 81]], dtype=int32)

In [21]:
# Append

a = np.random.randint(1, 100, 15)
b = np.random.randint(1, 100, 24).reshape(6, 4)

np.append(a, 202) # append 202 as last element in a 
print(b.shape[0])
np.append(b, np.ones((b.shape[0], 1)), axis = 1) # append 1 in last col

6


array([[54.,  6., 17., 36.,  1.],
       [22., 14., 13., 16.,  1.],
       [76., 25., 30., 81.,  1.],
       [16., 69., 16.,  1.,  1.],
       [ 9., 95., 83.,  7.,  1.],
       [42., 64., 57., 85.,  1.]])

In [22]:
# Concatenate

a = np.arange(6).reshape(2, 3)
b = np.arange(6, 12).reshape(2, 3)

print(a)
print(b)

np.concatenate((a, b), axis = 0) # row wise -> vstack
np.concatenate((a, b), axis = 1) # col wise -> hstack

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [23]:
# Unique item

a = np.array([1, 2, 1, 2, 4, 5, 6, 5, 7, 9, 7, 3, 2])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [24]:
# Expand dimension

a = np.arange(1, 7).reshape(3, 2)
print(a)
print('\n')
b = np.expand_dims(a, axis = 0)
c = np.expand_dims(a, axis = 1)
# print(a.shape, b.shape)

print(b)
print('\n')
print(c)

[[1 2]
 [3 4]
 [5 6]]


[[[1 2]
  [3 4]
  [5 6]]]


[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [25]:
# Where value satisfy

a = np.random.randint(1, 100, 20)
np.where(a > 50) # return index only value > 50
np.where(a > 50, 0, 1) # replace 0 where true and replace 1 where false

array([1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [26]:
# Argmax / Argmin -> return max/min value index

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)
np.argmax(a) # max value index
np.argmin(a) # min value index

np.argmax(b, axis = 0)
np.argmin(b, axis = 1)

[ 4 68 65 17 27 98  1 43 11 84]
[[15 42 14 54]
 [57 91 85 50]
 [53 87 97 66]]


array([2, 3, 0])

In [27]:
# Cumsum & Cumprod -> sum of previous all

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.cumsum(a)
np.cumprod(a)

np.cumsum(b, axis = 0) # row
np.cumprod(b, axis = 1) # col

[89 29 49 18 48 21 52 40  3 97]
[[13 71  1 26]
 [36 53 30  3]
 [13 67 18 33]]


array([[    13,    923,    923,  23998],
       [    36,   1908,  57240, 171720],
       [    13,    871,  15678, 517374]])

In [28]:
# Percentile -> how many % people behind me

a = np.random.randint(1, 100, 10)
print(a)

print(np.sort(a))
np.percentile(a, 0) # min
np.percentile(a, 50) # mid
np.percentile(a, 100) # max

[23 74 35 68 14 90 18 92 74 84]
[14 18 23 35 68 74 74 84 90 92]


np.float64(92.0)

In [29]:
# Histogram -> frequency count in given range (bins)
    
a = np.random.randint(1, 100, 50)
print(a)
np.histogram(a, bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

[63 82 99 35 10 58 66 77 30 12 25 56 51  5 64 28 67 95  8  3 26 71 99 95
 60 94 64 29 64 47  7 13 66 20 54 38 42 42 41 41 57 94 29 87 46 67  6 21
 44 77]


(array([5, 3, 7, 3, 7, 5, 9, 3, 2, 6]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [30]:
# Corelation (ans lie in -1 to 1) & Coefficient

salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [31]:
# Isin -> search for multiple item

a = np.random.randint(1, 100, 20);
items = np.array([10, 20, 30, 40, 50, 60, 70])

print(a)
print(items)
np.isin(a, items)
a[np.isin(a, items)]

[96 45 50 18 83 95 44 86 98 81 10 54 29 94 37 49 84 92  3 88]
[10 20 30 40 50 60 70]


array([50, 10], dtype=int32)

In [32]:
# Flip -> reverse

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.flip(a)
np.flip(b) # row, col flip
np.flip(b, axis = 0) # row flip
np.flip(b, axis = 1) # col flip

[84 35 17 47  6 56 74 64 93  5]
[[74 35 52 16]
 [25 53 92 71]
 [30 86 96 15]]


array([[16, 52, 35, 74],
       [71, 92, 53, 25],
       [15, 96, 86, 30]], dtype=int32)

In [33]:
# Put -> replace specific element

a = np.random.randint(1, 100, 10)
print(a)

np.put(a, [0, 5, 2], [100, 200, 300])
a

[37 81 88 74 98 65 80 44  5 28]


array([100,  81, 300,  74,  98, 200,  80,  44,   5,  28], dtype=int32)

In [34]:
# Delete -> after delete return new array

a = np.random.randint(1, 100, 10)
b = np.random.randint(1, 100, 12).reshape(3, 4)
print(a)
print(b)

np.delete(a, 0)
np.delete(a, [0, 2, 3])
np.delete(b, 0, axis = 0)

[25  5 51 37 39 34 14 22 39 32]
[[ 5 96  6  9]
 [71 13 33 53]
 [82 26 88 14]]


array([[71, 13, 33, 53],
       [82, 26, 88, 14]], dtype=int32)

In [35]:
# Set function

m = np.array([1, 2, 3, 4, 5, 6])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)
np.intersect1d(m, n)
np.setdiff1d(m, n) # element in m not n
np.setxor1d(m, n) # remove common element
np.in1d(m, 2)

C:\Users\Asus\AppData\Local\Temp\ipykernel_21020\1598237902.py:10: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m, 2)


array([False,  True, False, False, False, False])

In [36]:
# Clip -> value in range

b = np.random.randint(1, 100, 20)
print(b)
np.clip(b, a_min = 5, a_max = 66)

[83 70 82 80 69 20 62 30 85 60 88 15 76 60 62 93 92 98 51 28]


array([66, 66, 66, 66, 66, 20, 62, 30, 66, 60, 66, 15, 66, 60, 62, 66, 66,
       66, 51, 28], dtype=int32)